### ISSUE TITLE
If the map is added to a page, the page is not loaded [Page Builder by Site Origin]

### ISSUE THREAD

**Issue by Claudia-10249** [Socrapop/travelers-map#16]
Hi,

I use your travelers map for my blog.
This has worked wonderfully until 1-2 weeks ago.
Since 1 week newly created blog pages are no longer being loaded as soon as I use the travelers map.

I create the pages with: 
- WordPress 5.7.1 with the Theme: Sydney
- Content View: Version 5.8.6; CV 2.4.0.1
- Page Builder by Site Origin: Version 2.12.0

Thanks in advance for your support.

**Comment by Socrapop** [comment]
Dear Claudia, 
Thank you for this bug report.
Someone on the Wordpress support forum posted an issue similar I think: 
https://wordpress.org/support/topic/conflict-with-page-builder-by-siteorigin-7/

The error comes from the plugin Page Builder by Site Origin which is not using the default Wordpress page generation, so Travelers' Map is unstable with their plugin.
Could you confirm it's a conflict with the page builder by trying to add a map to a page without the page builder ?

**Comment by Claudia-10249** [comment]
Hi,

Problem seems to be solved.

Thanks for your support and best wishes,
Claudia
