### ISSUE TITLE
Some errors adding a new post

### ISSUE THREAD

**Issue by zodit** [Socrapop/travelers-map#23]
Installing the plugin Wordpress displayed an error, i forgot the precise message, it was about the plugin outputting over 3000 errors, and Wordpress warned me that if i find errors about "header already sent" I should deactivate the plugin. I guess this has something to do with file codification (in other situations I had to delete some white spaces at the beginning of the files, and save them again).

Second issue: I am using a Custom Post Type called "annunci", I added a post. Before to save for the first time i read some errors in the plugin's metabox, immediately after the map and after the marker box:

Notice: Undefined variable: marker_data_array in
/home/zodit959/sub_demo/wp1/wp-content/plugins/travelers-map/includes/admin/cttm-admin.php on line 133

Notice: Undefined variable: marker_data_array in
/home/zodit959/sub_demo/wp1/wp-content/plugins/travelers-map/includes/admin/cttm-admin.php on line 136

Notice: Undefined variable: marker_data_array in
/home/zodit959/sub_demo/wp1/wp-content/plugins/travelers-map/includes/admin/cttm-admin.php on line 137

Perhaps something about PHP version or empty array? After the first publish, there are no errors on editing (marker_data_array may exist).

**Comment by zodit** [comment]
I think that the second issue is at the beginning of **cttm_meta_callback** function in cttm-admin.php 
The $marker_data_array is defined only if the condition is true, else it is not defined.

    function cttm_meta_callback($post)
        {
            wp_nonce_field(basename(__FILE__), 'cttm_nonce');
            if (metadata_exists('post', $post->ID, '_latlngmarker')) {
                $cttm_stored_meta = get_post_meta($post->ID, '_latlngmarker', true);
                $marker_data_array = json_decode($cttm_stored_meta, true);
        }
I tried to add an else statement, recreating some default array values, but I failed, some other errors appear, and the plugin is broken. Perhaps you can find a working solution?

**Comment by Socrapop** [comment]
Thank you for this bug report, it is indeed an error showing since PHP 8.0 (testing for a null variable before was returning false, and was not triggering a notice, it now does so you have to test if the variable isset before :))
Here is the commit fixing this 👍 https://github.com/Socrapop/travelers-map/commit/f47fccf1139e145959ed7640018efdc2f4eccffe
(it will be merged in version 2.1.0)
