### ISSUE TITLE
Adding interaction with external links

### ISSUE THREAD

**Issue by zodit** [Socrapop/travelers-map#25]
This is perhaps a new feature. Reading Leaflet's documentation i could not find a solution.
Is it possible to add an external link to activate a maker on the map?

In a (collapsible?) panel I would add a list of posts, with some ajax filters (filtering locations, post category, or type of marker). 
Each post has a link to activate the corresponding marker on the map, centering it, and opening the infobox. It is like a "store locator".

**Comment by zodit** [comment]
I've found a technique: adding attribute "title" to the markers, and a little function, then we can set some external links pointing at them like anchors.
The code is here, perhaps you can find something useful: http://jsfiddle.net/abenrob/ZkC5M/

**Comment by Socrapop** [comment]
Oops I missed this ticket!
The key element here is that all the markers are added to an array which is then used to target them (with the title in your example). For now in Travelers map there is no array storing the markers, so it is not yet possible to target the pop-ups.
But as I said in the other ticket, I'm planning to do that in the next update I think :)

**Comment by zodit** [comment]
Yes, it is a nice improvement, for now I am doing something similar in another project of mine, with a sidebar of links, and I would use a taxonomy to categorize my posts (I decided it's the taxonomy to set the different markers). 
On the other hands your plugin in more advanced and with clustered markers, for maps with many markers it is very good. Can't wait to see how you improve it.
