### ISSUE TITLE
Not working inside WPBakery Tabs

### ISSUE THREAD

**Issue by zodit** [Socrapop/travelers-map#26]
How to reproduce:  use WPBakery Page Builder. Add a Tabs widget, add a map shortcode inside the second tab (in the first one it is working). 

Result : the map is not working  when the second tab is opened. The map is broken with gray background and text: Travelers' Map is loading... If you see this after your page is loaded completely, leafletJS files are missing.

This is not true, leaflet.js and travelersmap-bundle.js are loaded.

Resizing the browser's window the map is restored.
I tried to force the refresh with a button firing initTravelersMap(); but in console i see this error: Uncaught ReferenceError: initTravelersMap is not defined.

I think it has something to do with hidden elements at first page load.

**Comment by Socrapop** [comment]
Dear zodit, thank you for the bug report.

I've added webpack to my javascript (travelersmap-bundle.js) in Travelers Map project some time ago, and you just pointed that initTravelersMap() is not accessible from outside the script anymore. It seems Webpack is concatenating all my functions inside an [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE), maiking them inaccessible, I will have [to attach it to the window object](https://stackoverflow.com/a/41797084) it seems.

**Comment by zodit** [comment]
Hello Camille, thank you for your reply, I was just reporting my experiments. Yes, I analyzed your code and finally I've found a workaround with invalidateSize(), as I discovered you put the maps in the cttm_map array, so, for a single map that I have in my page I ended with this JQuery snippet code:

    // force init Leaflet travelers map on tabs
    $('.vc_tta-tabs-list a').on( "click", function(e){
      setTimeout(function() {
        if (cttm_map != undefined) {
          console.log('existing map');
          // it's an array so a single map is zero
          cttm_map[0].invalidateSize();
        }
      }, 1000);
    });
  
It is not perfect, but for now I can manage, perhaps I should get the length of cttm_mao array, and then do a cycle to invalidate all maps eventually present in the page, do you know how this could be done?

**Comment by Socrapop** [comment]
Yes you can, in fact I wrote how to interact with the maps in the Getting Started page. I wrote a developers documentation in it : 
https://camilles-travels.com/get-started-with-travelers-map-wordpress-plugin/#dev-documentation

There is also a custom event triggered when the maps are loaded :)

**Comment by zodit** [comment]
Oh, cool, i missed that part, thank you.

**Comment by Socrapop** [comment]
No problem it's a bit hidden. I think one of the next feature would be to add a real Dev documentation, and more control over the markers objects (like the map object I think I should give the possibility to interact with markers objects globally) and maybe add some hooks and filter for popovers Content 😊

**Comment by zodit** [comment]
I added a comment in my other issue, to interact with markers, with external links opening popouts. Perhaps adding a title you solve?
