### ISSUE TITLE
Adding markers without a post

### ISSUE THREAD

**Issue by alexture** [Socrapop/travelers-map#29]
Hi! I'm creating a travel blog that also has crowd-source recommendations. I haven't been to these places, so I don't want to write articles about them and "pollute" the blog with just a title and an address and no content, but I really wish I could show them on the map manually.
I'm guessing that's a lot of work, but thought I'd mention it in case someone else has the same need! :)

**Comment by Socrapop** [comment]
Dear @alexture,

I've always avoided adding this feature to keep the plugin simple and easily understandable. I really want to keep it the way it is described :) :

> Geolocate your posts and display them on an interactive OpenStreetMap map using a simple shortcode. Customize your markers and map. 

Maybe that would be a paid option I could develop, but I don't really have time and motivation right now :/

However, what you could do is to create a new "post type" in Wordpress for those places. So you don't have to pollute your blog feed with those. Unfortunately, those would still have a link / popover on click.

Have a nice day,
Camille

**Comment by Dimitri-Basseguy** [comment]
You can also add multiple marker for one post :)
