### ISSUE TITLE
Infinite load-loop when meta-incomplete/wrong order

### ISSUE THREAD

**Issue by vd-meer-net** [Socrapop/travelers-map#34]
All my posts are automatically created with the meta-data and added with an api.
Till a few ago, I i used the meta-data in the following format:
```
{
    "multiplemarkers":  "false",
    "customtitle":  "",
    "customthumbnail":  0,
    "markerdata":  [
                       "https://########/#####/cttm_markers-trad.png",
                       32,
                       45
                   ],
    "longitude":  "5.766233",
    "customexcerpt":  "",
    "latitude":  "51.983217"
}
```

But if I use this format right know I get an infinite loading loop if I choose to edit the message. Viewing the message goes alright.

When I correct the metadata record to this format:
```
{
    "latitude": "51.983217",
    "longitude": "5.766233",
    "markerdata": [
        "https://########/#####/cttm_markers-trad.png",
        32,
        45
    ],
    "multiplemarkers": false,
    "customtitle": "",
    "customexcerpt": "",
    "customthumbnail": "0",
    "customanchor": ""
}
```
Editing works fine.

I will update my meta-data-generator, to generate the new format. But it took a long time to find this. And I think it should work if the json is in a little different order.

Further testing shows me that the order is not the problem.
The infinite load-loop occurs on editing **if the customanchor-value is missing.**

**Comment by Socrapop** [comment]
Thank you for the issue reporting. 
As you said in your last paragraph, the order is not problematic as each line is then exported as a php variable.

I will try to reproduce by adding manually, but not sure why it was causing infinite loading as there is a condition for the variable to exist in the js file : https://github.com/Socrapop/travelers-map/blob/bd284e2bbcf91f52e07fd19b326eb3ada8a36465/includes/public/js/init-travelers-map.js#L235

**Comment by Socrapop** [comment]
Ok, I tried in local and read your message again, your issue is in the edit page, and I can reproduce.
I will fix it in the next update.

**Comment by Socrapop** [comment]
Nevermind, the issue was that you set multiplemarker as a string `"false"`, where it should have been a boolean `false`.
This was causing an infinite loop because the plugin though your multiplemarker.
I still fixed it 👍 https://github.com/Socrapop/travelers-map/pull/41/commits/1491335fb606cda301f93eff8a04c9778d528864
Next update will have that change. #41
