### ISSUE TITLE
do_shortcode not working

### ISSUE THREAD

**Issue by AndrePhoto** [Socrapop/travelers-map#36]
Trying to use the shortcode via php using do_shortcode function always causes internal errors like http 500.

I simply tried to use the generated code like:
`$output = do_shortcode('[travelers-map this_post=true]');`

**Comment by Socrapop** [comment]
I'm closing this issue as it's old and I can't reproduce on a fresh install.
I'm pretty confident something else was causing the issue but feel free to reopen if you have more information to share about this.
